### ISSUE TITLE
UglifyJS setup broken

### ISSUE THREAD

**Issue by tmcw** [simple-statistics/simple-statistics#238]
```
~/src/simple-statistics〉./node_modules/.bin/uglifyjs dist/simple-statistics.js -c -m --source-map content="./dist/simple-statistics.js.map" -o dist/simple-statistics.min.js
WARN: Dropping unused variable define [dist/simple-statistics.js:1,333]
WARN: Dropping unused variable module [dist/simple-statistics.js:1,340]
WARN: Dropping unused variable exports [dist/simple-statistics.js:1,347]
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'content=./dist/simple-statistics.js.map'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1314:33)
    at done (/Users/tmcw/src/simple-statistics/node_modules/handlebars/node_modules/uglify-js/bin/uglifyjs:516:20)
    at cb (/Users/tmcw/src/simple-statistics/node_modules/handlebars/node_modules/uglify-js/bin/uglifyjs:324:39)
    at /Users/tmcw/src/simple-statistics/node_modules/handlebars/node_modules/uglify-js/bin/uglifyjs:391:9
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

🤷‍♂️ I wish [the --source-map docs were easier to read pre coffee](https://github.com/mishoo/UglifyJS2#cli-source-map-options)

**Comment by tmcw** [comment]
Oh. This is a bug in yarn, somehow. Yarn installs uglify-js 2.x in `./node_modules/.bin/uglifyjs`, not 3.x for some reason. Even though 3.x is a direct dependency and 2.x is a transitive. I should, but am not going to engage with that right now.
